# input file in TAB/CSV separated format
# first line is a header line with the following column names (in all caps):
# SAMPLE_ID, R1, R2, SAMPLE_TYPE
# subsequent lines contain individual data samples, with full path to R1 and R2 reads.
# SAMPLE_ID should not contain ANY SPECIAL CHARACTERS (e.g., |)
# SAMPLE_TYPE can be either data or ntc

# change this line to point to your data file
input: "../input.tab"

# read assessment options
ra_file_type: "raw"

# trimming options
trim_threads: 2
trim_file_type: "raw"
trim_min_qual: 10

# trimmed reads assessment
tra_file_type: "trimmed"

# kraken options
kraken_threads: 2
kraken_file_type: "trimmed"
kraken_opts: " "

# estimate genome size options
egs_file_type: "trimmed"
egs_min_kmer_count: 3
egs_kmer_len: 31
egs_mash_opts: " "

# assembly options
asm_file_type: "trimmed"
asm_memory: 6
asm_threads: 2
asm_shovill_opts: "--minlen 500"

# assembly assessment options
aa_threads: 2
aa_assembler: "shovill"
aa_file_type: "trimmed"
aa_quast_opts: "--contig-thresholds 0,500,1000,10000,50000,250000 --no-plots --no-html --no-icarus"

# serotyping options
sero_threads: 2
sero_assembler: "shovill"
sero_sistr_opts: " "

# abricate options
abr_assembler: "shovill"
abr_db: "ncbi"
abr_opts: "--minid 75 --mincov 0"
